# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Main properties
mod.java=25
mod.minecraft=26.1.2
mod.loader=0.19.1
loom_version=1.16-SNAPSHOT

# Mod properties
mod.group=me.shurik
mod.id=better-suggestions
mod.name=Better Suggestions
mod.description=Makes Minecraft command suggestions more useful.

# Dependencies
deps.fabricApi=0.145.4+26.1.2
deps.clothConfig=26.1.154+fabric
deps.modMenu=18.0.0-alpha.8